# .github/workflows/release.yml
name: Release

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      # 发布到 NPM Registry
      - name: Setup Node.js for NPM
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      - run: npm install
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 发布到 GitHub Packages
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
